name: Build and Deploy to Cloud Run

on:
    push:
        branches:
            - master

# Environment variables available to all jobs and steps in this workflow
env:
    PROJECT_ID: ${{ secrets.RUN_PROJECT }}
    RUN_REGION: asia-east1
    SERVICE_NAME: skills-online

jobs:
    setup-build-deploy:
        name: Setup, Build, and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            # Set Up Node JS
            - name: Set Node.js
              uses: actions/setup-node@master
              with:
                node-version: 12.x

            # Install dependencies
            - name: Install dependencies
              run: yarn install --prod --pure-lockfile

            # Gatsby Lint for check performance
            # - name: Lint
            #   run: yarn run lint

            # Gatsby Build
            - name: Build
              run: |
                  yarn run build
                  echo gatsby build 
                  ls

            # Setup gcloud CLI
            - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
              with:
                  version: '275.0.0'
                  service_account_email: ${{ secrets.SA_EMAIL }}
                  service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

            # Configure gcloud CLI
            - name: gcloud Set up
              run: |
                  gcloud config set project $PROJECT_ID
            # Build and push image to Google Container Registry
            - name: Build Submit
              run: |
                  gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
            # Deploy image to Cloud Run
            - name: Deploy
              run: |
                  gcloud run deploy $SERVICE_NAME \
                    --region $RUN_REGION \
                    --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
                    --platform managed
